from prompt_manager import build_prompt
from llm_client import generate_firmware_code
from code_validator import validate_and_clean_code
from firmware_writer import write_firmware
from platformio_runner import build_and_upload


def run_pipeline(user_command: str, upload: bool = False) -> None:
    print("[ORCH] Starting Machine Intelligence pipeline")

    # 1. Build strict prompt
    prompt = build_prompt(user_command)
    print("[ORCH] Prompt constructed")

    # 2. Generate firmware code using local LLM
    raw_code = generate_firmware_code(prompt)
    if not raw_code:
        print("[ORCH ERROR] LLM failed to generate code")
        return
    print("[ORCH] Code generated by LLM")

    # 3. Validate and clean code
    clean_code = validate_and_clean_code(raw_code)
    if not clean_code:
        print("[ORCH ERROR] Code validation failed")
        return
    print("[ORCH] Code validated")

    # 4. Write firmware to src/main.cpp
    if not write_firmware(clean_code):
        print("[ORCH ERROR] Firmware writing failed")
        return
    print("[ORCH] Firmware written to src/main.cpp")

    # 5. Build or upload firmware
    if upload:
        print("[ORCH] Upload enabled")
        success = build_and_upload()
    else:
        print("[ORCH] Build-only mode (no hardware required)")
        success = build_and_upload()

    if success:
        print("[ORCH] Pipeline completed successfully")
    else:
        print("[ORCH ERROR] PlatformIO step failed")


if __name__ == "__main__":
    # Change this command to anything you want
    command = "Blink LED on GPIO 2 every second"

    # upload=False means ESP32 not required
    run_pipeline(command, upload=False)
