from prompt_manager import build_prompt
from llm_client import generate_firmware_code
from code_validator import validate_and_clean_code
from firmware_writer import write_firmware
from platformio_runner import build_and_upload
from speech_input import get_voice_command


def run_pipeline(user_command: str, upload: bool = True) -> None:
    print("[ORCH] Starting Machine Intelligence pipeline")

    # 1. Build strict prompt
    prompt = build_prompt(user_command)
    print("[ORCH] Prompt constructed")

    # 2. Generate firmware code using local LLM
    raw_code = generate_firmware_code(prompt)
    if not raw_code:
        print("[ORCH ERROR] LLM failed to generate code")
        return
    print("[ORCH] Code generated by LLM")

    # 3. Validate and clean code
    clean_code = validate_and_clean_code(raw_code)
    if not clean_code:
        print("[ORCH ERROR] Code validation failed")
        return
    print("[ORCH] Code validated")

    # 4. Write firmware to src/main.cpp
    if not write_firmware(clean_code):
        print("[ORCH ERROR] Firmware writing failed")
        return
    print("[ORCH] Firmware written to src/main.cpp")

    # 5. Build and upload firmware
    if upload:
        print("[ORCH] Upload enabled")
    else:
        print("[ORCH] Build-only mode (no hardware required)")

    success = build_and_upload()

    if success:
        print("[ORCH] Pipeline completed successfully")
    else:
        print("[ORCH ERROR] PlatformIO step failed")


if __name__ == "__main__":
    print("[SYSTEM] Speak your command after the prompt")

    command = get_voice_command()

    if not command:
        print("[SYSTEM ERROR] No voice command detected. Exiting.")
        exit(1)

    # Always try upload; PlatformIO will handle detection
    run_pipeline(command, upload=True)